# Alembic Configuration File

[alembic]
# path to migration scripts
script_location = ./alembic

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with date and time
# file_template = %%(rev)s_%%(slug)s_%%(timestamp)s

# Logging configuration
# path to the location of the logging configuration file
log_file =

# Level to log at. When 'notset', the script logs at the default Python logging level (INFO by default)
log_level = INFO

# When set to "true" or "1", the script will output colorized console output (default true)
colorize =
# A list of source file patterns to include, separated by whitespace or newline.
# When including a model file as source, all of SQLAlchemy ORM's ModelBase-derived class
# objects within that file are considered.
source_locations =

# A list of source patterns to exclude
exclude_locations =

# A list of Python namespace packages or sub packages to include
include_packages =

# A comma-separated list of paths to add to sys.path, in order to provide access to Python packages
import_path = .

# Whether to render "SET search_path TO 'public'" in migration scripts
# (use when schemas other than 'public' are in use)
sqlalchemy.url = driver://user:password@localhost/dbname

# Context objects for rendering
# sqlalchemy.url = postgresql+asyncpg://user:password@localhost:5432/vendoor
# These objects are passed to the `context.configure()` function
# context_object1 = value
# context_object2 = value

[loggers]
keys = root,sqlalchemy.engine

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy.engine]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
